version: '3.8' 
services:
  levelup-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      # Nome da aplicação
      SPRING_APPLICATION_NAME: projeto_levelupapi
      
      # Configuração do banco de dados RDS usando IP diretamente
      SPRING_DATASOURCE_URL: jdbc:postgresql://172.31.0.2:5432/levelupapi
      SPRING_DATASOURCE_USERNAME: levelup_admin
      SPRING_DATASOURCE_PASSWORD: LevelUp123!
      
      # Configuração JWT
      APP_JWT_SECRET: chave_secreta_muito_longa_e_aleatoria_para_seguranca
      APP_JWT_EXPIRATION: 86400000
      
      # Perfil ativo
      SPRING_PROFILES_ACTIVE: prod
      
      # Configuração JPA
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s